<a href="https://colab.research.google.com/github/narmadhaprasanth/Pytorch_learning/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import matplotlib.pyplot as plt
import numpy as np

In [57]:
x = torch.ones(3,3)
print(x)
x = torch.rand(4,4)
print(x)
x = torch.zeros(5,5)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1859, 0.1268, 0.5044, 0.0249],
        [0.9927, 0.4840, 0.1964, 0.5392],
        [0.7286, 0.4251, 0.8007, 0.4809],
        [0.5444, 0.6628, 0.4027, 0.1653]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [58]:
x = torch.empty(2,2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[4.6869e-37, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.]])


In [59]:
x = torch.linspace(0,3,5)
print(x)

tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])


In [60]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


#Slicing tensors

In [61]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([4, 2])
tensor([2, 4, 6, 8])
tensor([1, 2])


In [62]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


#Reshaping tensors

In [63]:
print(x)
y = x.view(2,4)
print(y)
y = x.view(8,-1)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


#Simple tensor operations

In [64]:
x = torch.ones(3,2)
y = torch.ones(3,2)
z = x+y
print(z)
z = x-y
print(z)
z = x*y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [65]:
z = y.add(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [66]:
z = y.add_(x) #inplace addition
print(y)
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


#pytorch <>numpy

In [67]:
x_np = x.numpy()
print(x_np)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [68]:
py_x = torch.from_numpy(x_np)
print(py_x)
print(type(py_x), type(x_np))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [69]:
a = np.random.randn(5)
py_a = torch.from_numpy(a)
print(type(a), type(py_a))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [70]:
np.add(a,1,out=a)
print(a)
print(py_a)

[ 1.3865864   1.66224166 -0.10271187  2.40781628  3.46543148]
tensor([ 1.3866,  1.6622, -0.1027,  2.4078,  3.4654], dtype=torch.float64)


In [71]:
%%time
for i in range(100):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = a+b

CPU times: user 84.3 ms, sys: 0 ns, total: 84.3 ms
Wall time: 95.9 ms


In [72]:
%%time
for i in range(100):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  c = a+b

CPU times: user 18.7 ms, sys: 864 µs, total: 19.5 ms
Wall time: 21.9 ms


In [73]:
%%time
for i in range(10):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = a+b

CPU times: user 9.57 ms, sys: 0 ns, total: 9.57 ms
Wall time: 11.2 ms


In [74]:
%%time
for i in range(10):
  a = torch.randn([10000,10000])
  b = torch.randn([10000,10000])
  c = a+b

CPU times: user 18.6 s, sys: 191 ms, total: 18.8 s
Wall time: 18.8 s


#CUDA support


In [75]:
print(torch.cuda.device_count())

1


#how to add cuda
edit->notebook settings->hardware accelerator->GPU->save

In [76]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [0]:
cuda0 = torch.device("cuda:0")

In [78]:
a = torch.ones(2,4,device=cuda0)
b = torch.ones(2,4,device=cuda0)
c = a+b
print(a)
print(b)
print(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]], device='cuda:0')


In [79]:
%%time
for i in range(10):
  a = torch.randn(10000,10000,device=cuda0)
  b = torch.randn(10000,10000,device=cuda0)
  c = a+b

CPU times: user 1.08 ms, sys: 9 µs, total: 1.09 ms
Wall time: 1.29 ms


#Autograd

In [80]:
x = torch.ones([3,3], requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [81]:
y = x+5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [82]:
z = y*y + 1
print(z)

tensor([[37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.]], grad_fn=<AddBackward0>)


In [83]:
t = torch.sum(z)
print(t)

tensor(333., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [85]:
print(x.grad)

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])


In [86]:
x = torch.ones([3,2], requires_grad=True)
y = x+5
r = 1/(1+torch.exp(-y))
print(r)
s = torch.sum(r)
print(s)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor(5.9852, grad_fn=<SumBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [87]:
x = torch.ones([3,2], requires_grad=True)
y = x+5
r = 1/(1+torch.exp(-y))
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


#Autograd example that looks like what we have been doing

In [0]:
x = torch.randn([20,1], requires_grad=True)
y = 3*x - 2

In [0]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

y_hat = w*x + b
loss = torch.sum((y_hat - y)**2)

In [90]:
print(loss)

tensor(210.7475, grad_fn=<SumBackward0>)


In [0]:
loss.backward()


In [92]:
print(w.grad, b.grad)

tensor([-54.9799]) tensor([103.8451])


#Do it in loop

In [0]:
learning_rate = 0.01

In [0]:
w = torch.tensor([1.],requires_grad = True)
b = torch.tensor([1.],requires_grad = True)

In [95]:
print(w.item(), b.item())

1.0 1.0


In [96]:
for i in range(10):
  x = torch.randn([20,1])
  y = 3*x - 2
  
  y_hat = w*x + b
  loss = torch.sum((y_hat-y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    
    w.grad.zero_()
    b.grad.zero_()
    
  print(w.item(),b.item())

1.7647953033447266 -0.14572405815124512
2.280285120010376 -0.8140975832939148
2.4862117767333984 -1.256675124168396
2.658869504928589 -1.5199170112609863
2.6900086402893066 -1.6793675422668457
2.8360300064086914 -1.8489347696304321
2.8963890075683594 -1.9188742637634277
2.949171543121338 -1.94428551197052
2.959017753601074 -1.9612728357315063
2.9796953201293945 -1.9773904085159302


#Do it for larger problem

In [102]:
%%time
learning_rate = 0.001
N =1000000
epochs = 200

w = torch.randn([N], requires_grad = True)
b = torch.randn([1], requires_grad = True)

print(torch.mean(w).item(), b.item())

for i in range(epochs):
  x = torch.randn([N], requires_grad=True)
  y = torch.dot(3*torch.ones([N]), x) -2
  
  y_hat = torch.dot(w,x) + b
  loss = torch.sum((y_hat-y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    
    w.grad.zero_()
    b.grad.zero_()
    
  #print(torch.mean(w).item(), b.item())

0.0004070353461429477 -0.7379459738731384
CPU times: user 3.9 s, sys: 568 ms, total: 4.47 s
Wall time: 4.5 s


In [101]:
%%time
learning_rate = 0.001
N =1000000
epochs = 200

w = torch.randn([N], requires_grad = True, device=cuda0)
b = torch.randn([1], requires_grad = True, device=cuda0)

print(torch.mean(w).item(), b.item())

for i in range(epochs):
  x = torch.randn([N], requires_grad=True, device=cuda0)
  y = torch.dot(3*torch.ones([N], device=cuda0), x) -2
  
  y_hat = torch.dot(w,x) + b
  loss = torch.sum((y_hat-y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    
    w.grad.zero_()
    b.grad.zero_()
    
  #print(torch.mean(w).item(), b.item())

0.0019629052840173244 -0.8159432411193848
CPU times: user 172 ms, sys: 51.4 ms, total: 223 ms
Wall time: 229 ms
